# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-11 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_classmate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classmate',
        ),
    ]
